services:
  - type: web
    name: ranchoddas-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: MONGO_URI
        value: "mongodb+srv://PrathameshBhurke:Prathameshbhurke666@cluster0.ozajm.mongodb.net/hotel_db?retryWrites=true&w=majority&appName=Cluster0"
      - key: SECRET_KEY
        value: "your-secret-key"